export type Database = {
  public: {
    Tables: {
      programs: {
        Row: {
          id: number;
          title: string;
          university: string;
          country: string;
          tuition_fee: number;
          currency: string;
          duration_months: number;
          study_level: string;
          description: string;
          created_at: string;
        };
        Insert: {
          id?: number;
          title: string;
          university: string;
          country: string;
          tuition_fee: number;
          currency?: string;
          duration_months: number;
          study_level: string;
          description: string;
          created_at?: string;
        };
        Update: {
          id?: number;
          title?: string;
          university?: string;
          country?: string;
          tuition_fee?: number;
          currency?: string;
          duration_months?: number;
          study_level?: string;
          description?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          avatar_url: string | null;
          bio: string | null;
          education_level: string | null;
          study_interests: string | null;
          phone_number: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          education_level?: string | null;
          study_interests?: string | null;
          phone_number?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          education_level?: string | null;
          study_interests?: string | null;
          phone_number?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      bookmarks: {
        Row: {
          id: number;
          user_id: string;
          program_id: number;
          created_at: string;
        };
        Insert: {
          id?: number;
          user_id: string;
          program_id: number;
          created_at?: string;
        };
        Update: {
          id?: number;
          user_id?: string;
          program_id?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      JobOpportunity: {
        Row: {
          id: string;
          createdAt: string;
          card_summary: string;
          department: string;
          funding_status: string;
          full_title: string;
          title: string;
          type: 'PHD' | 'JOB';
          isPhd: boolean | null;
          isJob: boolean | null;
          company: string;
          country: string;
          city: string;
          description: string;
          requirements: string[];
          deadline: string | null;
          postedAt: string;
          applicationLink: string;
          source: string;
        };
        Insert: {
          id?: string;
          createdAt?: string;
          card_summary: string;
          department: string;
          funding_status: string;
          full_title: string;
          title: string;
          type: 'PHD' | 'JOB';
          isPhd?: boolean | null;
          isJob?: boolean | null;
          company: string;
          country: string;
          city: string;
          description: string;
          requirements: string[];
          deadline?: string | null;
          postedAt: string;
          applicationLink: string;
          source: string;
        };
        Update: {
          id?: string;
          createdAt?: string;
          card_summary?: string;
          department?: string;
          funding_status?: string;
          full_title?: string;
          title?: string;
          type?: 'PHD' | 'JOB';
          isPhd?: boolean | null;
          isJob?: boolean | null;
          company?: string;
          country?: string;
          city?: string;
          description?: string;
          requirements?: string[];
          deadline?: string | null;
          postedAt?: string;
          applicationLink?: string;
          source?: string;
        };
        Relationships: [];
      };

      canada_sources: {
        Row: {
          id: string;
          program_type: 'VISITING_RESEARCH' | 'INTERNSHIP' | 'PHD';
          strategy: 'GOOGLE_SEED' | 'CURATED' | 'OPPORTUNISTIC';
          seed_key: string | null;
          base_url: string;
          allow_paths: string[];
          block_paths: string[];
          max_depth: number;
          active: boolean;
          respect_robots: boolean;
          max_requests_per_run: number;
          min_delay_ms: number;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          program_type: 'VISITING_RESEARCH' | 'INTERNSHIP' | 'PHD';
          strategy: 'GOOGLE_SEED' | 'CURATED' | 'OPPORTUNISTIC';
          seed_key?: string | null;
          base_url: string;
          allow_paths?: string[];
          block_paths?: string[];
          max_depth?: number;
          active?: boolean;
          respect_robots?: boolean;
          max_requests_per_run?: number;
          min_delay_ms?: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          program_type?: 'VISITING_RESEARCH' | 'INTERNSHIP' | 'PHD';
          strategy?: 'GOOGLE_SEED' | 'CURATED' | 'OPPORTUNISTIC';
          seed_key?: string | null;
          base_url?: string;
          allow_paths?: string[];
          block_paths?: string[];
          max_depth?: number;
          active?: boolean;
          respect_robots?: boolean;
          max_requests_per_run?: number;
          min_delay_ms?: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };

      canada_opportunity: {
        Row: {
          id: string;
          program_type: 'VISITING_RESEARCH' | 'INTERNSHIP' | 'PHD';
          country: string;
          province: string | null;
          city: string | null;
          institution_name: string;
          department: string | null;
          lab_group: string | null;
          title_clean: string;
          nutshell_15_words: string;
          funding_type: 'FUNDED' | 'PARTIALLY_FUNDED' | 'EXTERNAL_FUNDING_OK' | 'SELF_FUNDED_OK' | 'UNKNOWN';
          funding_confidence: 'HIGH' | 'MEDIUM' | 'LOW';
          funding_evidence: string | null;
          international_allowed: 'YES' | 'NO' | 'UNKNOWN';
          eligibility_confidence: 'HIGH' | 'MEDIUM' | 'LOW';
          eligibility_notes: string | null;
          eligibility_evidence: string | null;
          start_term: string | null;
          deadline_date: string | null;
          deadline_confidence: 'HIGH' | 'MEDIUM' | 'LOW';
          deadline_evidence: string | null;
          application_url: string;
          source_url: string;
          canonical_url: string;
          last_verified_at: string;
          freshness_score: number;
          status: 'ACTIVE' | 'EXPIRED' | 'BLOCKED' | 'NEEDS_REVIEW';
          status_reason: string | null;
          content_hash: string;
          page_last_modified: string | null;
          etag: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          program_type: 'VISITING_RESEARCH' | 'INTERNSHIP' | 'PHD';
          country?: string;
          province?: string | null;
          city?: string | null;
          institution_name: string;
          department?: string | null;
          lab_group?: string | null;
          title_clean: string;
          nutshell_15_words: string;
          funding_type?: 'FUNDED' | 'PARTIALLY_FUNDED' | 'EXTERNAL_FUNDING_OK' | 'SELF_FUNDED_OK' | 'UNKNOWN';
          funding_confidence?: 'HIGH' | 'MEDIUM' | 'LOW';
          funding_evidence?: string | null;
          international_allowed?: 'YES' | 'NO' | 'UNKNOWN';
          eligibility_confidence?: 'HIGH' | 'MEDIUM' | 'LOW';
          eligibility_notes?: string | null;
          eligibility_evidence?: string | null;
          start_term?: string | null;
          deadline_date?: string | null;
          deadline_confidence?: 'HIGH' | 'MEDIUM' | 'LOW';
          deadline_evidence?: string | null;
          application_url: string;
          source_url: string;
          canonical_url: string;
          last_verified_at?: string;
          freshness_score?: number;
          status?: 'ACTIVE' | 'EXPIRED' | 'BLOCKED' | 'NEEDS_REVIEW';
          status_reason?: string | null;
          content_hash: string;
          page_last_modified?: string | null;
          etag?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          program_type?: 'VISITING_RESEARCH' | 'INTERNSHIP' | 'PHD';
          country?: string;
          province?: string | null;
          city?: string | null;
          institution_name?: string;
          department?: string | null;
          lab_group?: string | null;
          title_clean?: string;
          nutshell_15_words?: string;
          funding_type?: 'FUNDED' | 'PARTIALLY_FUNDED' | 'EXTERNAL_FUNDING_OK' | 'SELF_FUNDED_OK' | 'UNKNOWN';
          funding_confidence?: 'HIGH' | 'MEDIUM' | 'LOW';
          funding_evidence?: string | null;
          international_allowed?: 'YES' | 'NO' | 'UNKNOWN';
          eligibility_confidence?: 'HIGH' | 'MEDIUM' | 'LOW';
          eligibility_notes?: string | null;
          eligibility_evidence?: string | null;
          start_term?: string | null;
          deadline_date?: string | null;
          deadline_confidence?: 'HIGH' | 'MEDIUM' | 'LOW';
          deadline_evidence?: string | null;
          application_url?: string;
          source_url?: string;
          canonical_url?: string;
          last_verified_at?: string;
          freshness_score?: number;
          status?: 'ACTIVE' | 'EXPIRED' | 'BLOCKED' | 'NEEDS_REVIEW';
          status_reason?: string | null;
          content_hash?: string;
          page_last_modified?: string | null;
          etag?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };

      canada_fetch_logs: {
        Row: {
          id: string;
          action: 'DISCOVER' | 'VERIFY';
          status: 'OK' | 'NOT_MODIFIED' | 'BLOCKED' | 'ERROR';
          program_type: 'VISITING_RESEARCH' | 'INTERNSHIP' | 'PHD' | null;
          source_id: string | null;
          canonical_url: string | null;
          fetched_url: string;
          fetched_at: string;
          http_status: number | null;
          elapsed_ms: number | null;
          response_bytes: number | null;
          etag: string | null;
          page_last_modified: string | null;
          content_hash: string | null;
          blocked_reason: string | null;
          error_message: string | null;
        };
        Insert: {
          id?: string;
          action: 'DISCOVER' | 'VERIFY';
          status: 'OK' | 'NOT_MODIFIED' | 'BLOCKED' | 'ERROR';
          program_type?: 'VISITING_RESEARCH' | 'INTERNSHIP' | 'PHD' | null;
          source_id?: string | null;
          canonical_url?: string | null;
          fetched_url: string;
          fetched_at?: string;
          http_status?: number | null;
          elapsed_ms?: number | null;
          response_bytes?: number | null;
          etag?: string | null;
          page_last_modified?: string | null;
          content_hash?: string | null;
          blocked_reason?: string | null;
          error_message?: string | null;
        };
        Update: {
          id?: string;
          action?: 'DISCOVER' | 'VERIFY';
          status?: 'OK' | 'NOT_MODIFIED' | 'BLOCKED' | 'ERROR';
          program_type?: 'VISITING_RESEARCH' | 'INTERNSHIP' | 'PHD' | null;
          source_id?: string | null;
          canonical_url?: string | null;
          fetched_url?: string;
          fetched_at?: string;
          http_status?: number | null;
          elapsed_ms?: number | null;
          response_bytes?: number | null;
          etag?: string | null;
          page_last_modified?: string | null;
          content_hash?: string | null;
          blocked_reason?: string | null;
          error_message?: string | null;
        };
        Relationships: [];
      };

      canada_seed_stats: {
        Row: {
          id: string;
          seed_key: string;
          program_type: 'VISITING_RESEARCH' | 'INTERNSHIP' | 'PHD';
          strategy: 'GOOGLE_SEED' | 'CURATED' | 'OPPORTUNISTIC';
          runs_count: number;
          urls_found: number;
          accepted: number;
          blocked: number;
          expired: number;
          last_run_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          seed_key: string;
          program_type: 'VISITING_RESEARCH' | 'INTERNSHIP' | 'PHD';
          strategy: 'GOOGLE_SEED' | 'CURATED' | 'OPPORTUNISTIC';
          runs_count?: number;
          urls_found?: number;
          accepted?: number;
          blocked?: number;
          expired?: number;
          last_run_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          seed_key?: string;
          program_type?: 'VISITING_RESEARCH' | 'INTERNSHIP' | 'PHD';
          strategy?: 'GOOGLE_SEED' | 'CURATED' | 'OPPORTUNISTIC';
          runs_count?: number;
          urls_found?: number;
          accepted?: number;
          blocked?: number;
          expired?: number;
          last_run_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };

      canada_saved_search: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          program_types: Array<'VISITING_RESEARCH' | 'INTERNSHIP' | 'PHD'>;
          filters: unknown;
          enabled: boolean;
          notify_email: string | null;
          notify_webhook_url: string | null;
          last_notified_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          program_types?: Array<'VISITING_RESEARCH' | 'INTERNSHIP' | 'PHD'>;
          filters?: unknown;
          enabled?: boolean;
          notify_email?: string | null;
          notify_webhook_url?: string | null;
          last_notified_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          program_types?: Array<'VISITING_RESEARCH' | 'INTERNSHIP' | 'PHD'>;
          filters?: unknown;
          enabled?: boolean;
          notify_email?: string | null;
          notify_webhook_url?: string | null;
          last_notified_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

export type Program = Database['public']['Tables']['programs']['Row'];
export type Profile = Database['public']['Tables']['profiles']['Row'];
export type Bookmark = Database['public']['Tables']['bookmarks']['Row'];
export type JobOpportunity = Database['public']['Tables']['JobOpportunity']['Row'];
