-- Seed starter sources for Canada module (safe to re-run)

INSERT INTO public.canada_sources (
  program_type,
  strategy,
  seed_key,
  base_url,
  allow_paths,
  block_paths,
  max_depth,
  active,
  respect_robots,
  max_requests_per_run,
  min_delay_ms,
  notes
)
VALUES
  (
    'PHD',
    'CURATED',
    NULL,
    'https://cfdlab.ok.ubc.ca/open-positions/',
    ARRAY['/open-positions']::text[],
    ARRAY['/wp-admin', '/wp-login']::text[],
    1,
    true,
    true,
    15,
    1200,
    'UBC Okanagan CFD Lab open positions'
  ),
  (
    'PHD',
    'CURATED',
    NULL,
    'https://www.nanofactory.lab.mcgill.ca/open-positions',
    ARRAY['/open-positions']::text[],
    ARRAY[]::text[],
    1,
    true,
    true,
    15,
    1200,
    'McGill Nanofactory Lab open positions'
  ),
  (
    'PHD',
    'CURATED',
    NULL,
    'https://patricklee.mie.utoronto.ca/open-positions/',
    ARRAY['/open-positions']::text[],
    ARRAY['/wp-admin', '/wp-login']::text[],
    1,
    true,
    true,
    15,
    1200,
    'University of Toronto (Patrick Lee) open positions'
  ),
  (
    'PHD',
    'CURATED',
    NULL,
    'https://plb.ualberta.ca/available-positions/',
    ARRAY['/available-positions']::text[],
    ARRAY[]::text[],
    1,
    true,
    true,
    15,
    1200,
    'University of Alberta Plant Biotechnology Lab available positions'
  ),
  (
    'INTERNSHIP',
    'CURATED',
    NULL,
    'https://www.mitacs.ca/our-programs/globalink-research-internship-students/',
    ARRAY['/our-programs/globalink-research-internship-students']::text[],
    ARRAY[]::text[],
    1,
    true,
    true,
    10,
    1200,
    'Mitacs Globalink Research Internship (students)'
  ),
  (
    'INTERNSHIP',
    'CURATED',
    NULL,
    'https://inrs.ca/en/studies/research-internships/undergraduate-summer-research-internships/',
    ARRAY['/en/studies/research-internships']::text[],
    ARRAY[]::text[],
    1,
    true,
    true,
    10,
    1200,
    'INRS undergraduate summer research internships'
  ),
  (
    'VISITING_RESEARCH',
    'CURATED',
    NULL,
    'https://research.ucalgary.ca/research-services/funding/ucalgary-visiting-scholars-program',
    ARRAY['/research-services/funding/ucalgary-visiting-scholars-program']::text[],
    ARRAY[]::text[],
    1,
    true,
    true,
    10,
    1200,
    'University of Calgary Visiting Scholars Program'
  ),
  (
    'VISITING_RESEARCH',
    'CURATED',
    NULL,
    'https://uwaterloo.ca/legal-and-immigration-services/visitors-including-visiting-students-scholars-researchers',
    ARRAY['/legal-and-immigration-services/visitors-including-visiting-students-scholars-researchers']::text[],
    ARRAY[]::text[],
    1,
    true,
    true,
    10,
    1200,
    'University of Waterloo visiting researchers information'
  )
ON CONFLICT (program_type, strategy, base_url) DO NOTHING;
